# Generated by Django 5.2.6 on 2025-10-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_date_joined_user_first_name_user_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
    ]
